---
- name: Install Zsh
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: apt-get update
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Zsh
      ansible.builtin.apt:
        name: zsh
    - name: Install git
      ansible.builtin.copy:
        src: http://http://192.168.19.130/store/programs/git/install.yml
        dest: ./git
        remote_src: yes
    - include: /git/install.yml
    - name:  Change to zsh 
      become: yes
      user:
        name: "t"
        shell: /bin/zsh