---
- name: Install Zsh
  hosts: localhost
  become: yes
  become_method: sudo
  become_user: t
  tasks:
    - name: apt-get update
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Zsh
      ansible.builtin.apt:
        name: zsh
    - name: install Git
      ansible.builtin.apt:
        name: git
    - name:  Change to zsh 
      user:
        name: "t"
        shell: /bin/zsh
    - name: Download ohmyzsh
      ansible.builtin.get_url: 
        url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/ohmyzsh.sh
    - name:  install ohmyzsh 
      ansible.builtin.script:
        cmd: /tmp/ohmyzsh.sh