programs:
  - name: ulauncher
    locations:
      - type: directory
        origin:
          location: ./configs/ulauncher/ulauncher
          isLocal: true
        to:
          location: .config/ulauncher/
          isHome: true