---
- name: Remove Insomnia 
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: Remove insomnia
      ansible.builtin.apt:
        name: insomnia 
        state: absent
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes