---
- name: Remove vscode 
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: Remove vscode
      ansible.builtin.apt:
        name: vscode
        state: absent
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes